name: Keepalive Commit

on:
  schedule:
    - cron: "0 0 1 * *"

  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check last commit date
        id: last_commit
        run: |
          LAST_COMMIT_DATE=$(git log -1 --format=%ct)
          NOW=$(date +%s)
          DIFF=$(( (NOW - LAST_COMMIT_DATE) / 86400 ))
          echo "days=$DIFF" >> $GITHUB_OUTPUT

      - name: Update timestamp if stale
        if: steps.last_commit.outputs.days > 45
        run: |
          echo "Last keepalive: $(date -u)" > .keepalive.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .keepalive.txt
          git commit -m "chore: keepalive commit [skip ci]" || echo "No changes to commit"
          git push