name: Sync Canvas to Notion

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  sync-events:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Sync Canvas events to Notion
        run: python scripts/sync_canvas_to_notion.py
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}

